// source: intent.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = globalThis;

goog.exportSymbol('intent_hasashi_org_pathpilot.ParseIntentRequest', null, global);
goog.exportSymbol('intent_hasashi_org_pathpilot.ParseIntentResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
intent_hasashi_org_pathpilot.ParseIntentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(intent_hasashi_org_pathpilot.ParseIntentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  intent_hasashi_org_pathpilot.ParseIntentRequest.displayName = 'intent_hasashi_org_pathpilot.ParseIntentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
intent_hasashi_org_pathpilot.ParseIntentResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(intent_hasashi_org_pathpilot.ParseIntentResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  intent_hasashi_org_pathpilot.ParseIntentResponse.displayName = 'intent_hasashi_org_pathpilot.ParseIntentResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
intent_hasashi_org_pathpilot.ParseIntentRequest.prototype.toObject = function(opt_includeInstance) {
  return intent_hasashi_org_pathpilot.ParseIntentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!intent_hasashi_org_pathpilot.ParseIntentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
intent_hasashi_org_pathpilot.ParseIntentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
transcribedText: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!intent_hasashi_org_pathpilot.ParseIntentRequest}
 */
intent_hasashi_org_pathpilot.ParseIntentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new intent_hasashi_org_pathpilot.ParseIntentRequest;
  return intent_hasashi_org_pathpilot.ParseIntentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!intent_hasashi_org_pathpilot.ParseIntentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!intent_hasashi_org_pathpilot.ParseIntentRequest}
 */
intent_hasashi_org_pathpilot.ParseIntentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTranscribedText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
intent_hasashi_org_pathpilot.ParseIntentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  intent_hasashi_org_pathpilot.ParseIntentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!intent_hasashi_org_pathpilot.ParseIntentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
intent_hasashi_org_pathpilot.ParseIntentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTranscribedText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string transcribed_text = 1;
 * @return {string}
 */
intent_hasashi_org_pathpilot.ParseIntentRequest.prototype.getTranscribedText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!intent_hasashi_org_pathpilot.ParseIntentRequest} returns this
 */
intent_hasashi_org_pathpilot.ParseIntentRequest.prototype.setTranscribedText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.toObject = function(opt_includeInstance) {
  return intent_hasashi_org_pathpilot.ParseIntentResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!intent_hasashi_org_pathpilot.ParseIntentResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
intent: jspb.Message.getFieldWithDefault(msg, 1, ""),
destination: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
category: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
originalText: jspb.Message.getFieldWithDefault(msg, 5, ""),
timestamp: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!intent_hasashi_org_pathpilot.ParseIntentResponse}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new intent_hasashi_org_pathpilot.ParseIntentResponse;
  return intent_hasashi_org_pathpilot.ParseIntentResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!intent_hasashi_org_pathpilot.ParseIntentResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!intent_hasashi_org_pathpilot.ParseIntentResponse}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setIntent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setDestination(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setCategory(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setOriginalText(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  intent_hasashi_org_pathpilot.ParseIntentResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!intent_hasashi_org_pathpilot.ParseIntentResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIntent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getOriginalText();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTimestamp();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string intent = 1;
 * @return {string}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.getIntent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!intent_hasashi_org_pathpilot.ParseIntentResponse} returns this
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.setIntent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string destination = 2;
 * @return {string}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.getDestination = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!intent_hasashi_org_pathpilot.ParseIntentResponse} returns this
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.setDestination = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!intent_hasashi_org_pathpilot.ParseIntentResponse} returns this
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.clearDestination = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.hasDestination = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string category = 3;
 * @return {string}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!intent_hasashi_org_pathpilot.ParseIntentResponse} returns this
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.setCategory = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!intent_hasashi_org_pathpilot.ParseIntentResponse} returns this
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.clearCategory = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.hasCategory = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional float confidence = 4;
 * @return {number}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!intent_hasashi_org_pathpilot.ParseIntentResponse} returns this
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional string original_text = 5;
 * @return {string}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.getOriginalText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!intent_hasashi_org_pathpilot.ParseIntentResponse} returns this
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.setOriginalText = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string timestamp = 6;
 * @return {string}
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.getTimestamp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!intent_hasashi_org_pathpilot.ParseIntentResponse} returns this
 */
intent_hasashi_org_pathpilot.ParseIntentResponse.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, intent_hasashi_org_pathpilot);
