# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'intent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cintent.proto\x12\x06intent\".\n\x12ParseIntentRequest\x12\x18\n\x10transcribed_text\x18\x01 \x01(\t\"\xb1\x01\n\x13ParseIntentResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x18\n\x0b\x64\x65stination\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x63\x61tegory\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x15\n\roriginal_text\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\tB\x0e\n\x0c_destinationB\x0b\n\t_category2Y\n\rIntentService\x12H\n\x0bParseIntent\x12\x1a.intent.ParseIntentRequest\x1a\x1b.intent.ParseIntentResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSEINTENTREQUEST']._serialized_start=24
  _globals['_PARSEINTENTREQUEST']._serialized_end=70
  _globals['_PARSEINTENTRESPONSE']._serialized_start=73
  _globals['_PARSEINTENTRESPONSE']._serialized_end=250
  _globals['_INTENTSERVICE']._serialized_start=252
  _globals['_INTENTSERVICE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
